//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cardrly.Resources.Lan {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cardrly.Resources.Lan.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate another Device.
        /// </summary>
        internal static string btnActivateanotherDevice {
            get {
                return ResourceManager.GetString("btnActivateanotherDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string btnEdit {
            get {
                return ResourceManager.GetString("btnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit links.
        /// </summary>
        internal static string btnEditLinks {
            get {
                return ResourceManager.GetString("btnEditLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string btnLogin {
            get {
                return ResourceManager.GetString("btnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed.
        /// </summary>
        internal static string btnPassed {
            get {
                return ResourceManager.GetString("btnPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string btnPreview {
            get {
                return ResourceManager.GetString("btnPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming.
        /// </summary>
        internal static string btnUpcoming {
            get {
                return ResourceManager.GetString("btnUpcoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Card.
        /// </summary>
        internal static string hdrAddCard {
            get {
                return ResourceManager.GetString("hdrAddCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        internal static string hdrCalendar {
            get {
                return ResourceManager.GetString("hdrCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cards.
        /// </summary>
        internal static string hdrCards {
            get {
                return ResourceManager.GetString("hdrCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string hdrComments {
            get {
                return ResourceManager.GetString("hdrComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Lead.
        /// </summary>
        internal static string hdrCreateLead {
            get {
                return ResourceManager.GetString("hdrCreateLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Card.
        /// </summary>
        internal static string hdrEditCard {
            get {
                return ResourceManager.GetString("hdrEditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Lead.
        /// </summary>
        internal static string hdrEditLead {
            get {
                return ResourceManager.GetString("hdrEditLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string hdrHome {
            get {
                return ResourceManager.GetString("hdrHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leads.
        /// </summary>
        internal static string hdrLeads {
            get {
                return ResourceManager.GetString("hdrLeads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Category.
        /// </summary>
        internal static string hdrLinkCategory {
            get {
                return ResourceManager.GetString("hdrLinkCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        internal static string hdrMore {
            get {
                return ResourceManager.GetString("hdrMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Links.
        /// </summary>
        internal static string hdrMyLinks {
            get {
                return ResourceManager.GetString("hdrMyLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Cardrly Device.
        /// </summary>
        internal static string lblACD {
            get {
                return ResourceManager.GetString("lblACD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate at.
        /// </summary>
        internal static string lblActivateat {
            get {
                return ResourceManager.GetString("lblActivateat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Remove.
        /// </summary>
        internal static string lblAdd_Remove {
            get {
                return ResourceManager.GetString("lblAdd/Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Comment.
        /// </summary>
        internal static string lblAddComment {
            get {
                return ResourceManager.GetString("lblAddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string lblAddress {
            get {
                return ResourceManager.GetString("lblAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        internal static string lblArabic {
            get {
                return ResourceManager.GetString("lblArabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bio.
        /// </summary>
        internal static string lblBio {
            get {
                return ResourceManager.GetString("lblBio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business.
        /// </summary>
        internal static string lblBusiness {
            get {
                return ResourceManager.GetString("lblBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call.
        /// </summary>
        internal static string lblCall {
            get {
                return ResourceManager.GetString("lblCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card.
        /// </summary>
        internal static string lblCard {
            get {
                return ResourceManager.GetString("lblCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Link Type.
        /// </summary>
        internal static string lblCardLinkType {
            get {
                return ResourceManager.GetString("lblCardLinkType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Name.
        /// </summary>
        internal static string lblCardName {
            get {
                return ResourceManager.GetString("lblCardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card theme.
        /// </summary>
        internal static string lblCardtheme {
            get {
                return ResourceManager.GetString("lblCardtheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Views.
        /// </summary>
        internal static string lblCardViews {
            get {
                return ResourceManager.GetString("lblCardViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the Device you are activating.
        /// </summary>
        internal static string lblChoosetheDeviceyouareactivating {
            get {
                return ResourceManager.GetString("lblChoosetheDeviceyouareactivating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Card Data.
        /// </summary>
        internal static string lblClearCardData {
            get {
                return ResourceManager.GetString("lblClearCardData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string lblComment {
            get {
                return ResourceManager.GetString("lblComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string lblCompany {
            get {
                return ResourceManager.GetString("lblCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string lblContact {
            get {
                return ResourceManager.GetString("lblContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Card.
        /// </summary>
        internal static string lblDeleteCard {
            get {
                return ResourceManager.GetString("lblDeleteCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Lead.
        /// </summary>
        internal static string lblDeleteLead {
            get {
                return ResourceManager.GetString("lblDeleteLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Photo.
        /// </summary>
        internal static string lblEdit_Photo {
            get {
                return ResourceManager.GetString("lblEdit Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string lblEnglish {
            get {
                return ResourceManager.GetString("lblEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expire.
        /// </summary>
        internal static string lblExpire {
            get {
                return ResourceManager.GetString("lblExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        internal static string lblFAQ {
            get {
                return ResourceManager.GetString("lblFAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string lblFrom {
            get {
                return ResourceManager.GetString("lblFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string lblFullName {
            get {
                return ResourceManager.GetString("lblFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help &amp; Support.
        /// </summary>
        internal static string lblHelpSupport {
            get {
                return ResourceManager.GetString("lblHelpSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Share To Users.
        /// </summary>
        internal static string lblIs_ShareToUsers {
            get {
                return ResourceManager.GetString("lblIs ShareToUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job title.
        /// </summary>
        internal static string lblJob_title {
            get {
                return ResourceManager.GetString("lblJob title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string lblLanguage {
            get {
                return ResourceManager.GetString("lblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead Category.
        /// </summary>
        internal static string lblLeadCategory {
            get {
                return ResourceManager.GetString("lblLeadCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leads Registered.
        /// </summary>
        internal static string lblLeadsRegistered {
            get {
                return ResourceManager.GetString("lblLeadsRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        internal static string lblLink {
            get {
                return ResourceManager.GetString("lblLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Clicks.
        /// </summary>
        internal static string lblLinkClicks {
            get {
                return ResourceManager.GetString("lblLinkClicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link color.
        /// </summary>
        internal static string lblLinkColor {
            get {
                return ResourceManager.GetString("lblLinkColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string lblLocation {
            get {
                return ResourceManager.GetString("lblLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string lblLogout {
            get {
                return ResourceManager.GetString("lblLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Devices.
        /// </summary>
        internal static string lblMyDevices {
            get {
                return ResourceManager.GetString("lblMyDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string lblName {
            get {
                return ResourceManager.GetString("lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OR.
        /// </summary>
        internal static string lblOR {
            get {
                return ResourceManager.GetString("lblOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person name.
        /// </summary>
        internal static string lblPersonName {
            get {
                return ResourceManager.GetString("lblPersonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person nickname.
        /// </summary>
        internal static string lblPersonnickname {
            get {
                return ResourceManager.GetString("lblPersonnickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string lblPhone_Number {
            get {
                return ResourceManager.GetString("lblPhone Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Photo.
        /// </summary>
        internal static string lblPickPhoto {
            get {
                return ResourceManager.GetString("lblPickPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Contacts.
        /// </summary>
        internal static string lblSaveContacts {
            get {
                return ResourceManager.GetString("lblSaveContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Card.
        /// </summary>
        internal static string lblScanCard {
            get {
                return ResourceManager.GetString("lblScanCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan to share Card.
        /// </summary>
        internal static string lblSCS {
            get {
                return ResourceManager.GetString("lblSCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Card Link.
        /// </summary>
        internal static string lblShareCardLink {
            get {
                return ResourceManager.GetString("lblShareCardLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Lead.
        /// </summary>
        internal static string lblShareLead {
            get {
                return ResourceManager.GetString("lblShareLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Offline Card.
        /// </summary>
        internal static string lblShareOfflineCard {
            get {
                return ResourceManager.GetString("lblShareOfflineCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share VCard.
        /// </summary>
        internal static string lblShareVCard {
            get {
                return ResourceManager.GetString("lblShareVCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Comments.
        /// </summary>
        internal static string lblShowComments {
            get {
                return ResourceManager.GetString("lblShowComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Media.
        /// </summary>
        internal static string lblSocial_Media {
            get {
                return ResourceManager.GetString("lblSocial Media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Recording.
        /// </summary>
        internal static string lblStarRecording {
            get {
                return ResourceManager.GetString("lblStarRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Photo.
        /// </summary>
        internal static string lblTakePhoto {
            get {
                return ResourceManager.GetString("lblTakePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Count by Device System.
        /// </summary>
        internal static string lblTCDS {
            get {
                return ResourceManager.GetString("lblTCDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string lblTo {
            get {
                return ResourceManager.GetString("lblTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Clicks.
        /// </summary>
        internal static string lblTotalClicks {
            get {
                return ResourceManager.GetString("lblTotalClicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string lblUsers {
            get {
                return ResourceManager.GetString("lblUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string lblValue {
            get {
                return ResourceManager.GetString("lblValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebSite.
        /// </summary>
        internal static string lblWebSite {
            get {
                return ResourceManager.GetString("lblWebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string plcPassword {
            get {
                return ResourceManager.GetString("plcPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string plcSearch {
            get {
                return ResourceManager.GetString("plcSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string plcUserName {
            get {
                return ResourceManager.GetString("plcUserName", resourceCulture);
            }
        }
    }
}
