//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cardrly.Resources.Lan {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cardrly.Resources.Lan.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate another Device.
        /// </summary>
        internal static string btnActivateanotherDevice {
            get {
                return ResourceManager.GetString("btnActivateanotherDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string btnEdit {
            get {
                return ResourceManager.GetString("btnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit links.
        /// </summary>
        internal static string btnEditLinks {
            get {
                return ResourceManager.GetString("btnEditLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string btnLogin {
            get {
                return ResourceManager.GetString("btnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past.
        /// </summary>
        internal static string btnPassed {
            get {
                return ResourceManager.GetString("btnPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string btnPreview {
            get {
                return ResourceManager.GetString("btnPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming.
        /// </summary>
        internal static string btnUpcoming {
            get {
                return ResourceManager.GetString("btnUpcoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Card.
        /// </summary>
        internal static string hdrAddCard {
            get {
                return ResourceManager.GetString("hdrAddCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        internal static string hdrCalendar {
            get {
                return ResourceManager.GetString("hdrCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cards.
        /// </summary>
        internal static string hdrCards {
            get {
                return ResourceManager.GetString("hdrCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string hdrComments {
            get {
                return ResourceManager.GetString("hdrComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Lead.
        /// </summary>
        internal static string hdrCreateLead {
            get {
                return ResourceManager.GetString("hdrCreateLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Card.
        /// </summary>
        internal static string hdrEditCard {
            get {
                return ResourceManager.GetString("hdrEditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Lead.
        /// </summary>
        internal static string hdrEditLead {
            get {
                return ResourceManager.GetString("hdrEditLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string hdrHome {
            get {
                return ResourceManager.GetString("hdrHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leads.
        /// </summary>
        internal static string hdrLeads {
            get {
                return ResourceManager.GetString("hdrLeads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Category.
        /// </summary>
        internal static string hdrLinkCategory {
            get {
                return ResourceManager.GetString("hdrLinkCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        internal static string hdrMore {
            get {
                return ResourceManager.GetString("hdrMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Links.
        /// </summary>
        internal static string hdrMyLinks {
            get {
                return ResourceManager.GetString("hdrMyLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        internal static string hdrSelectLanguage {
            get {
                return ResourceManager.GetString("hdrSelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Cardrly Device.
        /// </summary>
        internal static string lblACD {
            get {
                return ResourceManager.GetString("lblACD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate at.
        /// </summary>
        internal static string lblActivateat {
            get {
                return ResourceManager.GetString("lblActivateat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Remove.
        /// </summary>
        internal static string lblAdd_Remove {
            get {
                return ResourceManager.GetString("lblAdd/Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Comment.
        /// </summary>
        internal static string lblAddComment {
            get {
                return ResourceManager.GetString("lblAddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string lblAddress {
            get {
                return ResourceManager.GetString("lblAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bio.
        /// </summary>
        internal static string lblBio {
            get {
                return ResourceManager.GetString("lblBio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business.
        /// </summary>
        internal static string lblBusiness {
            get {
                return ResourceManager.GetString("lblBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call.
        /// </summary>
        internal static string lblCall {
            get {
                return ResourceManager.GetString("lblCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card.
        /// </summary>
        internal static string lblCard {
            get {
                return ResourceManager.GetString("lblCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Link Type.
        /// </summary>
        internal static string lblCardLinkType {
            get {
                return ResourceManager.GetString("lblCardLinkType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Name.
        /// </summary>
        internal static string lblCardName {
            get {
                return ResourceManager.GetString("lblCardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card theme.
        /// </summary>
        internal static string lblCardtheme {
            get {
                return ResourceManager.GetString("lblCardtheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Views.
        /// </summary>
        internal static string lblCardViews {
            get {
                return ResourceManager.GetString("lblCardViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the Device you are activating.
        /// </summary>
        internal static string lblChoosetheDeviceyouareactivating {
            get {
                return ResourceManager.GetString("lblChoosetheDeviceyouareactivating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Card Data.
        /// </summary>
        internal static string lblClearCardData {
            get {
                return ResourceManager.GetString("lblClearCardData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string lblComment {
            get {
                return ResourceManager.GetString("lblComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string lblCompany {
            get {
                return ResourceManager.GetString("lblCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string lblContact {
            get {
                return ResourceManager.GetString("lblContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Card.
        /// </summary>
        internal static string lblDeleteCard {
            get {
                return ResourceManager.GetString("lblDeleteCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Lead.
        /// </summary>
        internal static string lblDeleteLead {
            get {
                return ResourceManager.GetString("lblDeleteLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Photo.
        /// </summary>
        internal static string lblEdit_Photo {
            get {
                return ResourceManager.GetString("lblEdit Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Name.
        /// </summary>
        internal static string lblEvent_Name {
            get {
                return ResourceManager.GetString("lblEvent Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Type.
        /// </summary>
        internal static string lblEventType {
            get {
                return ResourceManager.GetString("lblEventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expire.
        /// </summary>
        internal static string lblExpire {
            get {
                return ResourceManager.GetString("lblExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        internal static string lblFAQ {
            get {
                return ResourceManager.GetString("lblFAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string lblFrom {
            get {
                return ResourceManager.GetString("lblFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string lblFullName {
            get {
                return ResourceManager.GetString("lblFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guests Number.
        /// </summary>
        internal static string lblGuestsNumber {
            get {
                return ResourceManager.GetString("lblGuestsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help &amp; Support.
        /// </summary>
        internal static string lblHelpSupport {
            get {
                return ResourceManager.GetString("lblHelpSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Share To Users.
        /// </summary>
        internal static string lblIs_ShareToUsers {
            get {
                return ResourceManager.GetString("lblIs ShareToUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job title.
        /// </summary>
        internal static string lblJob_title {
            get {
                return ResourceManager.GetString("lblJob title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join now.
        /// </summary>
        internal static string lblJoinnow {
            get {
                return ResourceManager.GetString("lblJoinnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string lblLanguage {
            get {
                return ResourceManager.GetString("lblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead Category.
        /// </summary>
        internal static string lblLeadCategory {
            get {
                return ResourceManager.GetString("lblLeadCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead Count.
        /// </summary>
        internal static string lblLeadCount {
            get {
                return ResourceManager.GetString("lblLeadCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leads Registered.
        /// </summary>
        internal static string lblLeadsRegistered {
            get {
                return ResourceManager.GetString("lblLeadsRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        internal static string lblLink {
            get {
                return ResourceManager.GetString("lblLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Clicks.
        /// </summary>
        internal static string lblLinkClicks {
            get {
                return ResourceManager.GetString("lblLinkClicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link color.
        /// </summary>
        internal static string lblLinkColor {
            get {
                return ResourceManager.GetString("lblLinkColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string lblLocation {
            get {
                return ResourceManager.GetString("lblLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string lblLogout {
            get {
                return ResourceManager.GetString("lblLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Devices.
        /// </summary>
        internal static string lblMyDevices {
            get {
                return ResourceManager.GetString("lblMyDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string lblName {
            get {
                return ResourceManager.GetString("lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OR.
        /// </summary>
        internal static string lblOR {
            get {
                return ResourceManager.GetString("lblOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person name.
        /// </summary>
        internal static string lblPersonName {
            get {
                return ResourceManager.GetString("lblPersonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person nickname.
        /// </summary>
        internal static string lblPersonnickname {
            get {
                return ResourceManager.GetString("lblPersonnickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string lblPhone_Number {
            get {
                return ResourceManager.GetString("lblPhone Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Photo.
        /// </summary>
        internal static string lblPickPhoto {
            get {
                return ResourceManager.GetString("lblPickPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Contacts.
        /// </summary>
        internal static string lblSaveContacts {
            get {
                return ResourceManager.GetString("lblSaveContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Card.
        /// </summary>
        internal static string lblScanCard {
            get {
                return ResourceManager.GetString("lblScanCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan to share Card.
        /// </summary>
        internal static string lblSCS {
            get {
                return ResourceManager.GetString("lblSCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Card Link.
        /// </summary>
        internal static string lblShareCardLink {
            get {
                return ResourceManager.GetString("lblShareCardLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Lead.
        /// </summary>
        internal static string lblShareLead {
            get {
                return ResourceManager.GetString("lblShareLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Offline Card.
        /// </summary>
        internal static string lblShareOfflineCard {
            get {
                return ResourceManager.GetString("lblShareOfflineCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share VCard.
        /// </summary>
        internal static string lblShareVCard {
            get {
                return ResourceManager.GetString("lblShareVCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Comments.
        /// </summary>
        internal static string lblShowComments {
            get {
                return ResourceManager.GetString("lblShowComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Media.
        /// </summary>
        internal static string lblSocial_Media {
            get {
                return ResourceManager.GetString("lblSocial Media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Recording.
        /// </summary>
        internal static string lblStarRecording {
            get {
                return ResourceManager.GetString("lblStarRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Photo.
        /// </summary>
        internal static string lblTakePhoto {
            get {
                return ResourceManager.GetString("lblTakePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Count by Device System.
        /// </summary>
        internal static string lblTCDS {
            get {
                return ResourceManager.GetString("lblTCDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Zone.
        /// </summary>
        internal static string lblTimeZone {
            get {
                return ResourceManager.GetString("lblTimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string lblTo {
            get {
                return ResourceManager.GetString("lblTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Clicks.
        /// </summary>
        internal static string lblTotalClicks {
            get {
                return ResourceManager.GetString("lblTotalClicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string lblUsers {
            get {
                return ResourceManager.GetString("lblUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string lblValue {
            get {
                return ResourceManager.GetString("lblValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebSite.
        /// </summary>
        internal static string lblWebSite {
            get {
                return ResourceManager.GetString("lblWebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred:.
        /// </summary>
        internal static string msgAnerroroccurred {
            get {
                return ResourceManager.GetString("msgAnerroroccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio file not saved. Please try again..
        /// </summary>
        internal static string msgAudiofilenotsavedPleasetryagain {
            get {
                return ResourceManager.GetString("msgAudiofilenotsavedPleasetryagain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera not supported.
        /// </summary>
        internal static string msgCameranotsupported {
            get {
                return ResourceManager.GetString("msgCameranotsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t Delete This Lead Now Try again Later..
        /// </summary>
        internal static string msgCan_tDeleteThisLeadNowTryagainLater {
            get {
                return ResourceManager.GetString("msgCan\'tDeleteThisLeadNowTryagainLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The To Date Must be greater Than From Date..
        /// </summary>
        internal static string msgDate_HomePage {
            get {
                return ResourceManager.GetString("msgDate_HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Device.
        /// </summary>
        internal static string msgDeleteDevice {
            get {
                return ResourceManager.GetString("msgDeleteDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this device?.
        /// </summary>
        internal static string msgDeleteDevice_qu {
            get {
                return ResourceManager.GetString("msgDeleteDevice_qu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete This Lead?.
        /// </summary>
        internal static string msgDeleteLead {
            get {
                return ResourceManager.GetString("msgDeleteLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Added Successfully..
        /// </summary>
        internal static string msgDeviceAddedSuccessfully {
            get {
                return ResourceManager.GetString("msgDeviceAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to Logout ?.
        /// </summary>
        internal static string msgDoYouWantToLogout {
            get {
                return ResourceManager.GetString("msgDoYouWantToLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Recording.
        /// </summary>
        internal static string msgEndRecording {
            get {
                return ResourceManager.GetString("msgEndRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during speech recognition:.
        /// </summary>
        internal static string msgErrorduringspeechrecognition {
            get {
                return ResourceManager.GetString("msgErrorduringspeechrecognition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Change Status..
        /// </summary>
        internal static string msgFailedToChangeStatus {
            get {
                return ResourceManager.GetString("msgFailedToChangeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Required : Card Name.
        /// </summary>
        internal static string msgFRCardName {
            get {
                return ResourceManager.GetString("msgFRCardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Required : Comment.
        /// </summary>
        internal static string msgFRComment {
            get {
                return ResourceManager.GetString("msgFRComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Required : Email.
        /// </summary>
        internal static string msgFREmail {
            get {
                return ResourceManager.GetString("msgFREmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Required : Full Name.
        /// </summary>
        internal static string msgFRFullName {
            get {
                return ResourceManager.GetString("msgFRFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Required : Link.
        /// </summary>
        internal static string msgFRLink {
            get {
                return ResourceManager.GetString("msgFRLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;From&quot; Date Should be Start From Now.
        /// </summary>
        internal static string msgFromDateShouldbeStartFromNow {
            get {
                return ResourceManager.GetString("msgFromDateShouldbeStartFromNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Required : Password.
        /// </summary>
        internal static string msgFRPassword {
            get {
                return ResourceManager.GetString("msgFRPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Required : User Name.
        /// </summary>
        internal static string msgFRUserName {
            get {
                return ResourceManager.GetString("msgFRUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Required : Value.
        /// </summary>
        internal static string msgFRValue {
            get {
                return ResourceManager.GetString("msgFRValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead Deleted Successfully.
        /// </summary>
        internal static string msgLeadDeletedSuccessfully {
            get {
                return ResourceManager.GetString("msgLeadDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This lead don&apos;t have email..
        /// </summary>
        internal static string msgLeadEmail {
            get {
                return ResourceManager.GetString("msgLeadEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This lead don&apos;t have Phone Number..
        /// </summary>
        internal static string msgLeadPhone {
            get {
                return ResourceManager.GetString("msgLeadPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Image.
        /// </summary>
        internal static string msgLoadingImage {
            get {
                return ResourceManager.GetString("msgLoadingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microphone access is required to record audio..
        /// </summary>
        internal static string msgMicrophoneaccessisrequiredtorecordaudio_ {
            get {
                return ResourceManager.GetString("msgMicrophoneaccessisrequiredtorecordaudio.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string msgNo {
            get {
                return ResourceManager.GetString("msgNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Activated Devices.
        /// </summary>
        internal static string msgNoActivatedDevices {
            get {
                return ResourceManager.GetString("msgNoActivatedDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ID found in the Qr..
        /// </summary>
        internal static string msgNoIDfoundintheQr {
            get {
                return ResourceManager.GetString("msgNoIDfoundintheQr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string msgOk {
            get {
                return ResourceManager.GetString("msgOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Image First.
        /// </summary>
        internal static string msgPleaseSelectImageFirst {
            get {
                return ResourceManager.GetString("msgPleaseSelectImageFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording started....
        /// </summary>
        internal static string msgRecordingstarted {
            get {
                return ResourceManager.GetString("msgRecordingstarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service is currently down. Please try again later..
        /// </summary>
        internal static string msgServicedown {
            get {
                return ResourceManager.GetString("msgServicedown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech not recognized. Please try again..
        /// </summary>
        internal static string msgSpeechnotrecognizedPleasetryagain {
            get {
                return ResourceManager.GetString("msgSpeechnotrecognizedPleasetryagain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech recognition failed:.
        /// </summary>
        internal static string msgSpeechrecognitionfailed {
            get {
                return ResourceManager.GetString("msgSpeechrecognitionfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Add Card..
        /// </summary>
        internal static string msgSuccessfullyAddCard {
            get {
                return ResourceManager.GetString("msgSuccessfullyAddCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Add Comment..
        /// </summary>
        internal static string msgSuccessfullyAddComment {
            get {
                return ResourceManager.GetString("msgSuccessfullyAddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Add Lead..
        /// </summary>
        internal static string msgSuccessfullyAddLead {
            get {
                return ResourceManager.GetString("msgSuccessfullyAddLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Add Link..
        /// </summary>
        internal static string msgSuccessfullyAddLink {
            get {
                return ResourceManager.GetString("msgSuccessfullyAddLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Reordered..
        /// </summary>
        internal static string msgSuccessfullyReordered {
            get {
                return ResourceManager.GetString("msgSuccessfullyReordered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Scan Card..
        /// </summary>
        internal static string msgSuccessfullyScanCard {
            get {
                return ResourceManager.GetString("msgSuccessfullyScanCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Update Card..
        /// </summary>
        internal static string msgSuccessfullyUpdateCard {
            get {
                return ResourceManager.GetString("msgSuccessfullyUpdateCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Update Lead..
        /// </summary>
        internal static string msgSuccessfullyUpdateLead {
            get {
                return ResourceManager.GetString("msgSuccessfullyUpdateLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Update Link..
        /// </summary>
        internal static string msgSuccessfullyUpdateLink {
            get {
                return ResourceManager.GetString("msgSuccessfullyUpdateLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device has not been deleted..
        /// </summary>
        internal static string msgTheDeviceHasNotBeenDeleted_ {
            get {
                return ResourceManager.GetString("msgTheDeviceHasNotBeenDeleted.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value not match Card Link Type..
        /// </summary>
        internal static string msgThevaluenotmatchCardLinkType {
            get {
                return ResourceManager.GetString("msgThevaluenotmatchCardLinkType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value not match link format..
        /// </summary>
        internal static string msgThevaluenotmatchlinkformat {
            get {
                return ResourceManager.GetString("msgThevaluenotmatchlinkformat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;To&quot; Date Should be less Than Today Date.
        /// </summary>
        internal static string msgTODateShouldbelessThanTodayDate {
            get {
                return ResourceManager.GetString("msgTODateShouldbelessThanTodayDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred. Please restart the app or contact support..
        /// </summary>
        internal static string msgUnexpected {
            get {
                return ResourceManager.GetString("msgUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string msgWarning {
            get {
                return ResourceManager.GetString("msgWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete This Card?.
        /// </summary>
        internal static string msgWarning_qu {
            get {
                return ResourceManager.GetString("msgWarning_qu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string msgYes {
            get {
                return ResourceManager.GetString("msgYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet connection!.
        /// </summary>
        internal static string No_Internet_connection {
            get {
                return ResourceManager.GetString("No_Internet_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Available Cards.
        /// </summary>
        internal static string plcNoAvailableCards {
            get {
                return ResourceManager.GetString("plcNoAvailableCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Available Events.
        /// </summary>
        internal static string PlcNoAvailableEvents {
            get {
                return ResourceManager.GetString("PlcNoAvailableEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Available Laeds.
        /// </summary>
        internal static string plcNoAvailableLaeds {
            get {
                return ResourceManager.GetString("plcNoAvailableLaeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Available Links.
        /// </summary>
        internal static string plcNoAvailableLinks {
            get {
                return ResourceManager.GetString("plcNoAvailableLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string plcPassword {
            get {
                return ResourceManager.GetString("plcPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string plcSearch {
            get {
                return ResourceManager.GetString("plcSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string plcUserName {
            get {
                return ResourceManager.GetString("plcUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
    }
}
